TramposoLibrary: src/InputManager.cpp File Reference
InputManager.cpp File Reference
#include "TramposoLibrary/InputManager.h"
#include <algorithm>
Variables
m_currentMouseState = SDL_GetMouseState(&m_mouseX, &m_mouseY)
<<<<<<< HEAD namespace TramposoLibrary { InputManager::InputManager() :m_keyboardState(SDL_GetKeyboardState(nullptr)), m_previousKeyboardState(SDL_NUM_SCANCODES, 0), m_currentMouseState(0), m_previousMouseState(0), m_mouseX(0), m_mouseY(0) { } void InputManager::update() { std::copy(m_keyboardState, m_keyboardState+SDL_NUM_SCANCODES, m_previousKeyboardState.begin());=======namespace TramposoLibrary { InputManager::InputManager() :m_keyboardState(SDL_GetKeyboardState(nullptr)) { std::fill_n(m_previousKeyboardState, SDL_NUM_SCANCODES, 0);} void InputManager::update() { std::copy_n(m_keyboardState, SDL_NUM_SCANCODES, m_previousKeyboardState);> > > > > > ff39892716f02024ee20b509f89751aa88d65f92 m_previousMouseState = m_currentMouseState
Variable Documentation
m_currentMouseState
m_currentMouseState = SDL_GetMouseState(&m_mouseX, &m_mouseY)
Definition at line 30 of file InputManager.cpp.
Referenced by TramposoLibrary::InputManager::isMouseButtonHeld(), TramposoLibrary::InputManager::isMouseButtonPressed(), and TramposoLibrary::InputManager::isMouseButtonReleased().
m_previousMouseState
<<<<<<< HEAD namespace TramposoLibrary { InputManager::InputManager() : m_keyboardState(SDL_GetKeyboardState(nullptr)), m_previousKeyboardState(SDL_NUM_SCANCODES, 0), m_currentMouseState(0), m_previousMouseState(0), m_mouseX(0), m_mouseY(0) { } void InputManager::update() { std::copy(m_keyboardState, m_keyboardState + SDL_NUM_SCANCODES, m_previousKeyboardState.begin()); ======= namespace TramposoLibrary { InputManager::InputManager() : m_keyboardState(SDL_GetKeyboardState(nullptr)) { std::fill_n(m_previousKeyboardState, SDL_NUM_SCANCODES, 0); } void InputManager::update() { std::copy_n(m_keyboardState, SDL_NUM_SCANCODES, m_previousKeyboardState); >>>>>> ff39892716f02024ee20b509f89751aa88d65f92 m_previousMouseState = m_currentMouseState
Definition at line 29 of file InputManager.cpp.
Referenced by TramposoLibrary::InputManager::isMouseButtonPressed(), and TramposoLibrary::InputManager::isMouseButtonReleased().