TramposoLibrary: TramposoLibrary::Game Class Reference
TramposoLibrary::Game Class Reference
The main class for managing the game loop and core systems.
#include <Game.h>
Public Member Functions
void addScene (const std::string &name, std::unique_ptr< Scene > scene)
Add a new scene to the game.
Game (const std::string &title, int width, int height)
Construct a new Game object.
AudioManager & getAudioManager ()
Get the audio manager.
CollisionManager & getCollisionManager ()
Get the collision manager.
InputManager & getInputManager ()
Get the input manager.
SDL_Renderer * getRenderer () const
Get the SDL renderer.
bool isRunning () const
Check if the game is currently running.
void quit ()
Signal the game to quit.
void run ()
Start the main game loop.
void setCurrentScene (const std::string &name)
Set the current active scene.
~Game ()
Destroy the Game object and clean up resources.
Private Member Functions
void handleEvents ()
void render ()
void update (float deltaTime)
Private Attributes
std::unique_ptr< AudioManager > m_audioManager
std::unique_ptr< CollisionManager > m_collisionManager
Scene * m_currentScene
std::unique_ptr< InputManager > m_inputManager
bool m_isRunning
Uint32 m_lastFrameTime
SDL_Renderer * m_renderer
std::unordered_map< std::string, std::unique_ptr< Scene > > m_scenes
SDL_Window * m_window
Detailed Description
The main class for managing the game loop and core systems.
The Game class is responsible for initializing SDL, managing scenes, and running the main game loop.
Definition at line 24 of file Game.h.
Constructor & Destructor Documentation
Game()
TramposoLibrary::Game::Game (const std::string & title, int width, int height)
Construct a new Game object.
Parameters
title The title of the game window.
width The width of the game window.
height The height of the game window.
Definition at line 10 of file Game.cpp.
References m_audioManager, m_collisionManager, m_inputManager, m_renderer, and m_window.
~Game()
TramposoLibrary::Game::~Game ()
Destroy the Game object and clean up resources.
Definition at line 35 of file Game.cpp.
References m_renderer, and m_window.
Member Function Documentation
addScene()
void TramposoLibrary::Game::addScene (const std::string & name, std::unique_ptr< Scene > scene)
Add a new scene to the game.
Parameters
name The name of the scene, used as a key for retrieval.
scene A unique pointer to the Scene object.
Definition at line 96 of file Game.cpp.
References m_scenes.
Referenced by main().
getAudioManager()
AudioManager & TramposoLibrary::Game::getAudioManager () inline
Get the audio manager.
Returns
AudioManager& A reference to the audio manager.
Definition at line 88 of file Game.h.
References m_audioManager.
Referenced by CatchGameScene::load(), and CatchGameScene::update().
getCollisionManager()
CollisionManager & TramposoLibrary::Game::getCollisionManager () inline
Get the collision manager.
Returns
CollisionManager& A reference to the collision manager.
Definition at line 97 of file Game.h.
References m_collisionManager.
Referenced by CatchGameScene::load(), CatchGameScene::unload(), and CatchGameScene::update().
getInputManager()
InputManager & TramposoLibrary::Game::getInputManager () inline
Get the input manager.
Returns
InputManager& A reference to the input manager.
Definition at line 79 of file Game.h.
References m_inputManager.
Referenced by CatchGameScene::update().
getRenderer()
SDL_Renderer * TramposoLibrary::Game::getRenderer () const
Get the SDL renderer.
Returns
SDL_Renderer* A pointer to the SDL renderer.
Definition at line 114 of file Game.cpp.
References m_renderer.
Referenced by CatchGameScene::load().
handleEvents()
void TramposoLibrary::Game::handleEvents () private
Definition at line 63 of file Game.cpp.
References m_inputManager, and m_isRunning.
Referenced by run().
isRunning()
bool TramposoLibrary::Game::isRunning () const
Check if the game is currently running.
Returns
true If the game is running.
false If the game is not running.
Definition at line 118 of file Game.cpp.
References m_isRunning.
quit()
void TramposoLibrary::Game::quit ()
Signal the game to quit.
Definition at line 92 of file Game.cpp.
References m_isRunning.
Referenced by CatchGameScene::update().
render()
void TramposoLibrary::Game::render () private
Definition at line 81 of file Game.cpp.
References m_currentScene, m_renderer, and TramposoLibrary::Scene::render().
Referenced by run().
run()
void TramposoLibrary::Game::run ()
Start the main game loop.
Definition at line 42 of file Game.cpp.
References handleEvents(), m_isRunning, m_lastFrameTime, render(), and update().
Referenced by main().
setCurrentScene()
void TramposoLibrary::Game::setCurrentScene (const std::string & name)
Set the current active scene.
Parameters
name The name of the scene to set as active.
Definition at line 100 of file Game.cpp.
References TramposoLibrary::Scene::load(), m_currentScene, m_scenes, and TramposoLibrary::Scene::unload().
Referenced by main().
update()
void TramposoLibrary::Game::update (float deltaTime) private
Definition at line 73 of file Game.cpp.
References m_collisionManager, m_currentScene, m_inputManager, and TramposoLibrary::Scene::update().
Referenced by run().
Member Data Documentation
m_audioManager
std::unique_ptr<AudioManager> TramposoLibrary::Game::m_audioManager private
Definition at line 115 of file Game.h.
Referenced by Game(), and getAudioManager().
m_collisionManager
std::unique_ptr<CollisionManager> TramposoLibrary::Game::m_collisionManager private
Definition at line 116 of file Game.h.
Referenced by Game(), getCollisionManager(), and update().
m_currentScene
Scene* TramposoLibrary::Game::m_currentScene private
Definition at line 119 of file Game.h.
Referenced by render(), setCurrentScene(), and update().
m_inputManager
std::unique_ptr<InputManager> TramposoLibrary::Game::m_inputManager private
Definition at line 114 of file Game.h.
Referenced by Game(), getInputManager(), handleEvents(), and update().
m_isRunning
bool TramposoLibrary::Game::m_isRunning private
Definition at line 112 of file Game.h.
Referenced by handleEvents(), isRunning(), quit(), and run().
m_lastFrameTime
Uint32 TramposoLibrary::Game::m_lastFrameTime private
Definition at line 121 of file Game.h.
Referenced by run().
m_renderer
SDL_Renderer* TramposoLibrary::Game::m_renderer private
Definition at line 111 of file Game.h.
Referenced by Game(), getRenderer(), render(), and ~Game().
m_scenes
std::unordered_map<std::string, std::unique_ptr<Scene> > TramposoLibrary::Game::m_scenes private
Definition at line 118 of file Game.h.
Referenced by addScene(), and setCurrentScene().
m_window
SDL_Window* TramposoLibrary::Game::m_window private
Definition at line 110 of file Game.h.
Referenced by Game(), and ~Game().
The documentation for this class was generated from the following files:
include/TramposoLibrary/Game.h
src/Game.cpp