TramposoLibrary: TramposoLibrary::Scene Class Reference
TramposoLibrary::Scene Class Reference abstract
Represents a game scene or state.
#include <Scene.h>
Public Member Functions
void addSprite (std::shared_ptr< Sprite > sprite)
Add a sprite to the scene.
virtual void load ()=0
Load resources and initialize the scene.
virtual void render ()
Render the scene and its sprites.
Scene (Game *game)
Construct a new Scene object.
virtual void unload ()=0
Unload resources and clean up the scene.
virtual void update (float deltaTime)=0
Update the scene and its sprites.
virtual ~Scene ()=default
Destroy the Scene object.
Protected Attributes
Game * m_game
std::vector< std::shared_ptr< Sprite > > m_sprites
Detailed Description
Represents a game scene or state.
The Scene class manages a collection of sprites and provides methods for updating and rendering the scene.
Definition at line 19 of file Scene.h.
Constructor & Destructor Documentation
Scene()
TramposoLibrary::Scene::Scene (Game * game)
Construct a new Scene object.
Parameters
game A pointer to the Game object that owns this scene.
Definition at line 6 of file Scene.cpp.
~Scene()
virtual TramposoLibrary::Scene::~Scene () virtual default
Destroy the Scene object.
Member Function Documentation
addSprite()
void TramposoLibrary::Scene::addSprite (std::shared_ptr< Sprite > sprite)
Add a sprite to the scene.
Parameters
sprite A shared pointer to the Sprite to add.
Definition at line 8 of file Scene.cpp.
References m_sprites.
Referenced by CatchGameScene::load().
load()
virtual void TramposoLibrary::Scene::load () pure virtual
Load resources and initialize the scene.
This method is called when the scene becomes active.
Implemented in CatchGameScene.
Referenced by TramposoLibrary::Game::setCurrentScene().
render()
virtual void TramposoLibrary::Scene::render () virtual
Render the scene and its sprites.
Reimplemented in CatchGameScene.
Referenced by TramposoLibrary::Game::render().
unload()
virtual void TramposoLibrary::Scene::unload () pure virtual
Unload resources and clean up the scene.
This method is called when the scene is no longer active.
Implemented in CatchGameScene.
Referenced by TramposoLibrary::Game::setCurrentScene().
update()
virtual void TramposoLibrary::Scene::update (float deltaTime) pure virtual
Update the scene and its sprites.
Parameters
deltaTime The time elapsed since the last update.
Implemented in CatchGameScene.
Referenced by TramposoLibrary::Game::update().
Member Data Documentation
m_game
Game* TramposoLibrary::Scene::m_game protected
Definition at line 68 of file Scene.h.
Referenced by CatchGameScene::load(), CatchGameScene::unload(), and CatchGameScene::update().
m_sprites
std::vector<std::shared_ptr<Sprite> > TramposoLibrary::Scene::m_sprites protected
Definition at line 69 of file Scene.h.
Referenced by addSprite().
The documentation for this class was generated from the following files:
include/TramposoLibrary/Scene.h
src/Scene.cpp