TramposoLibrary: TramposoLibrary::CollisionManager Class Reference
TramposoLibrary::CollisionManager Class Reference
#include <CollisionManager.h>
Public Member Functions
void addCollider (const std::string &name, const SDL_Rect &rect)
bool checkCollision (const std::string &name1, const std::string &name2)
void checkCollisions ()
void removeCollider (const std::string &name)
void updateCollider (const std::string &name, const SDL_Rect &rect)
Private Attributes
std::unordered_map< std::string, SDL_Rect > m_colliders
Detailed Description
Definition at line 10 of file CollisionManager.h.
Member Function Documentation
addCollider()
void TramposoLibrary::CollisionManager::addCollider (const std::string & name, const SDL_Rect & rect)
Definition at line 5 of file CollisionManager.cpp.
References m_colliders.
Referenced by CatchGameScene::load().
checkCollision()
bool TramposoLibrary::CollisionManager::checkCollision (const std::string & name1, const std::string & name2)
Definition at line 17 of file CollisionManager.cpp.
References m_colliders.
Referenced by checkCollisions(), and CatchGameScene::update().
checkCollisions()
void TramposoLibrary::CollisionManager::checkCollisions ()
Definition at line 34 of file CollisionManager.cpp.
References checkCollision(), and m_colliders.
removeCollider()
void TramposoLibrary::CollisionManager::removeCollider (const std::string & name)
Definition at line 9 of file CollisionManager.cpp.
References m_colliders.
Referenced by CatchGameScene::unload().
updateCollider()
void TramposoLibrary::CollisionManager::updateCollider (const std::string & name, const SDL_Rect & rect)
Definition at line 13 of file CollisionManager.cpp.
References m_colliders.
Referenced by CatchGameScene::update().
Member Data Documentation
m_colliders
std::unordered_map<std::string, SDL_Rect> TramposoLibrary::CollisionManager::m_colliders private
Definition at line 19 of file CollisionManager.h.
Referenced by addCollider(), checkCollision(), checkCollisions(), removeCollider(), and updateCollider().
The documentation for this class was generated from the following files:
include/TramposoLibrary/CollisionManager.h
src/CollisionManager.cpp