TramposoLibrary: TramposoLibrary::AudioManager Class Reference
TramposoLibrary::AudioManager Class Reference
#include <AudioManager.h>
Public Member Functions
AudioManager ()
void loadMusic (const std::string &filename)
void loadSound (const std::string &name, const std::string &filename)
void pauseMusic ()
void playMusic ()
void playSound (const std::string &name)
void resumeMusic ()
void stopMusic ()
~AudioManager ()
Private Attributes
Mix_Music * m_music
std::unordered_map< std::string, Mix_Chunk * > m_soundEffects
Detailed Description
Definition at line 10 of file AudioManager.h.
Constructor & Destructor Documentation
AudioManager()
TramposoLibrary::AudioManager::AudioManager ()
~AudioManager()
TramposoLibrary::AudioManager::~AudioManager ()
Member Function Documentation
loadMusic()
void TramposoLibrary::AudioManager::loadMusic (const std::string & filename)
Referenced by CatchGameScene::load().
loadSound()
void TramposoLibrary::AudioManager::loadSound (const std::string & name, const std::string & filename)
Referenced by CatchGameScene::load().
pauseMusic()
void TramposoLibrary::AudioManager::pauseMusic ()
playMusic()
void TramposoLibrary::AudioManager::playMusic ()
Referenced by CatchGameScene::load().
playSound()
void TramposoLibrary::AudioManager::playSound (const std::string & name)
Referenced by CatchGameScene::update().
resumeMusic()
void TramposoLibrary::AudioManager::resumeMusic ()
stopMusic()
void TramposoLibrary::AudioManager::stopMusic ()
Member Data Documentation
m_music
Mix_Music* TramposoLibrary::AudioManager::m_music private
Definition at line 26 of file AudioManager.h.
m_soundEffects
std::unordered_map<std::string, Mix_Chunk*> TramposoLibrary::AudioManager::m_soundEffects private
Definition at line 25 of file AudioManager.h.
The documentation for this class was generated from the following file:
include/TramposoLibrary/AudioManager.h