TramposoLibrary: CatchGameScene Class Reference
CatchGameScene Class Reference
Public Member Functions
CatchGameScene (TramposoLibrary::Game *game)
void load () override
Load resources and initialize the scene.
void render () override
Render the scene and its sprites.
void unload () override
Unload resources and clean up the scene.
void update (float deltaTime) override
Update the scene and its sprites.
Public Member Functions inherited from TramposoLibrary::Scene
void addSprite (std::shared_ptr< Sprite > sprite)
Add a sprite to the scene.
Scene (Game *game)
Construct a new Scene object.
virtual ~Scene ()=default
Destroy the Scene object.
Private Member Functions
void resetFallingObject ()
Private Attributes
std::shared_ptr< TramposoLibrary::Sprite > m_fallingObject
std::shared_ptr< TramposoLibrary::Sprite > m_player
int m_score
Additional Inherited Members
Protected Attributes inherited from TramposoLibrary::Scene
Game * m_game
std::vector< std::shared_ptr< Sprite > > m_sprites
Detailed Description
Definition at line 12 of file CatchGame.cpp.
Constructor & Destructor Documentation
CatchGameScene()
CatchGameScene::CatchGameScene (TramposoLibrary::Game * game) inline
Definition at line 14 of file CatchGame.cpp.
Member Function Documentation
load()
void CatchGameScene::load () inline override virtual
Load resources and initialize the scene.
This method is called when the scene becomes active.
Implements TramposoLibrary::Scene.
Definition at line 16 of file CatchGame.cpp.
References TramposoLibrary::CollisionManager::addCollider(), TramposoLibrary::Scene::addSprite(), TramposoLibrary::Game::getAudioManager(), TramposoLibrary::Game::getCollisionManager(), TramposoLibrary::Sprite::getRect(), TramposoLibrary::Game::getRenderer(), TramposoLibrary::AudioManager::loadMusic(), TramposoLibrary::AudioManager::loadSound(), m_fallingObject, TramposoLibrary::Scene::m_game, m_player, and TramposoLibrary::AudioManager::playMusic().
render()
void CatchGameScene::render () inline override virtual
Render the scene and its sprites.
Reimplemented from TramposoLibrary::Scene.
Definition at line 71 of file CatchGame.cpp.
References m_score.
resetFallingObject()
void CatchGameScene::resetFallingObject () inline private
Definition at line 88 of file CatchGame.cpp.
References m_fallingObject, and TramposoLibrary::Sprite::setPosition().
Referenced by update().
unload()
void CatchGameScene::unload () inline override virtual
Unload resources and clean up the scene.
This method is called when the scene is no longer active.
Implements TramposoLibrary::Scene.
Definition at line 78 of file CatchGame.cpp.
References TramposoLibrary::Game::getCollisionManager(), TramposoLibrary::Scene::m_game, and TramposoLibrary::CollisionManager::removeCollider().
update()
void CatchGameScene::update (float deltaTime) inline override virtual
Update the scene and its sprites.
Parameters
deltaTime The time elapsed since the last update.
Implements TramposoLibrary::Scene.
Definition at line 35 of file CatchGame.cpp.
References TramposoLibrary::CollisionManager::checkCollision(), TramposoLibrary::Game::getAudioManager(), TramposoLibrary::Game::getCollisionManager(), TramposoLibrary::Game::getInputManager(), TramposoLibrary::Sprite::getRect(), m_fallingObject, TramposoLibrary::Scene::m_game, m_player, m_score, TramposoLibrary::AudioManager::playSound(), TramposoLibrary::Game::quit(), resetFallingObject(), TramposoLibrary::Sprite::setPosition(), and TramposoLibrary::CollisionManager::updateCollider().
Member Data Documentation
m_fallingObject
std::shared_ptr<TramposoLibrary::Sprite> CatchGameScene::m_fallingObject private
Definition at line 85 of file CatchGame.cpp.
Referenced by load(), resetFallingObject(), and update().
m_player
std::shared_ptr<TramposoLibrary::Sprite> CatchGameScene::m_player private
Definition at line 84 of file CatchGame.cpp.
Referenced by load(), and update().
m_score
int CatchGameScene::m_score private
Definition at line 86 of file CatchGame.cpp.
Referenced by render(), and update().
The documentation for this class was generated from the following file:
src/CatchGame.cpp